package com.fdmgroup.icms.classes;

import java.util.Calendar;
import java.util.Date;

import org.springframework.beans.factory.config.ConfigurableBeanFactory;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.context.annotation.Scope;

@Configuration
public class IcmsBeanConfig {
	
	private static long issueIdCounter; //TODO the unique issueId should be generated by the database
	
	@Bean
	@Scope(value = ConfigurableBeanFactory.SCOPE_PROTOTYPE)
	public Issue issue() {
		Date currentTime = Calendar.getInstance().getTime();
		
		Issue newIssue = new Issue(issueIdCounter, currentTime);
		++issueIdCounter;
		
		return newIssue;
	}
}
